Repository vuesion/vuesion, pull requests merged in 2018-07, with the labels that each got.

#179 feat(components): add cookie consent
  src/app/app/App/App.vue
  src/app/app/actions.spec.ts
  src/app/app/actions.ts
  src/app/app/getters.spec.ts
  src/app/app/getters.ts
  src/app/app/mutations.spec.ts
  src/app/app/mutations.ts
  src/app/app/state.ts
  src/app/shared/animations/FadeAnimation/FadeAnimation.spec.ts
  src/app/shared/animations/FadeAnimation/FadeAnimation.vue
  src/app/shared/components/VueCarousel/VueCarousel.vue
  src/app/shared/components/VueCookieConsent/VueCookieConsent.spec.ts
  src/app/shared/components/VueCookieConsent/VueCookieConsent.stories.ts
  src/app/shared/components/VueCookieConsent/VueCookieConsent.vue
  src/app/shared/styles/_variables.scss
Labels: feature

#183 refactor(vuex): change default-state object to a factory function
  docs/guide/clean-up.md
  docs/guide/styles.md
  src/app/app/actions.spec.ts
  src/app/app/getters.spec.ts
  src/app/app/module.ts
  src/app/app/mutations.spec.ts
  src/app/app/state.ts
  src/app/counter/actions.spec.ts
  src/app/counter/getters.spec.ts
  src/app/counter/module.ts
  src/app/counter/mutations.spec.ts
  src/app/counter/state.ts
  src/app/shared/styles/_variables.scss
  src/app/state.ts
  tools/generators/ast.ts
  tools/generators/connected/connected.spec.ts.hbs
  tools/generators/module/actions.spec.ts.hbs
  tools/generators/module/getters.spec.ts.hbs
  tools/generators/module/module.ts.hbs
  tools/generators/module/mutations.spec.ts.hbs
  tools/generators/module/state.ts.hbs
Labels: enhancement

#189 fix: proper 404 page
  cypress/integration/404.spec.ts
  src/server/isomorphic.ts
Labels: bug

#190 docs: localization for zh-cn
  README.md
  docs/.vuepress/config.js
  docs/zh-cn/README.md
  docs/zh-cn/docs/i18n.md
  docs/zh-cn/docs/npm-scripts.md
  docs/zh-cn/docs/storybook.md
  docs/zh-cn/docs/style-guide.md
  docs/zh-cn/guide/build.md
  docs/zh-cn/guide/clean-up.md
  docs/zh-cn/guide/cli.md
  docs/zh-cn/guide/config.md
  docs/zh-cn/guide/contribute.md
  docs/zh-cn/guide/i18n.md
  docs/zh-cn/guide/install.md
  docs/zh-cn/guide/run.md
  docs/zh-cn/guide/styles.md
  docs/zh-cn/guide/test.md
  docs/zh-cn/guide/update.md
  docs/zh-cn/guide/vuex.md
  docs/zh-cn/introduction.md
  i18n/de.json
  i18n/en.json
  i18n/pt.json
  i18n/zh-cn.json
  package.json
  src/app/app/App/App.vue
Labels: docs

#200 Add integration test for 404 HTTP status code
  cypress/integration/404.spec.ts
Labels: enhancement

#202 docs: first review finished, improve localization quality for zh-cn
  docs/zh-cn/README.md
  docs/zh-cn/docs/i18n.md
  docs/zh-cn/docs/npm-scripts.md
  docs/zh-cn/docs/storybook.md
  docs/zh-cn/docs/style-guide.md
  docs/zh-cn/guide/build.md
  docs/zh-cn/guide/clean-up.md
  docs/zh-cn/guide/cli.md
  docs/zh-cn/guide/config.md
  docs/zh-cn/guide/contribute.md
  docs/zh-cn/guide/i18n.md
  docs/zh-cn/guide/install.md
  docs/zh-cn/guide/run.md
  docs/zh-cn/guide/styles.md
  docs/zh-cn/guide/test.md
  docs/zh-cn/guide/update.md
  docs/zh-cn/guide/vuex.md
  docs/zh-cn/introduction.md
Labels: docs
