Repository vuesion/vuesion, pull requests merged in 2018-10, with the labels that each got.

#246 refactor(tests): improve test setup for connected components
  src/app/counter/Counter/Counter.spec.ts
  tools/generators/connected/connected.spec.ts.hbs
Labels: enhancement

#248 feat(vue-tab-group): add is-active property to pre-select tab-item
  src/app/components/Components/Components.vue
  src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts
  src/app/shared/components/VueTabGroup/VueTabGroup.stories.ts
  src/app/shared/components/VueTabGroup/VueTabGroup.vue
  src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.vue
Labels: enhancement, feature

#253 feat(i18n): update portuguese translations
  i18n/pt.json
Labels: i18n

#262 fix: action typings
  src/app/counter/actions.spec.ts
  src/app/counter/actions.ts
  tools/generators/module/actions.spec.ts.hbs
  tools/generators/module/actions.ts.hbs
Labels: DX

#256 feat(vue-data-table): add row to scoped slot; add sortable, fitContent
  src/app/components/Components/Components.spec.ts
  src/app/components/Components/Components.vue
  src/app/shared/components/VueDataTable/DataTableFixtures.ts
  src/app/shared/components/VueDataTable/IDataTable.ts
  src/app/shared/components/VueDataTable/VueDataTable.stories.ts
  src/app/shared/components/VueDataTable/VueDataTable.vue
  src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.spec.ts
  src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue
Labels: UI, feature

#263 feat(vue-tooltip): add property to programmatically suppress tooltip
  src/app/shared/components/VueTooltip/VueTooltip.spec.ts
  src/app/shared/components/VueTooltip/VueTooltip.stories.ts
  src/app/shared/components/VueTooltip/VueTooltip.vue
Labels: UI, feature

#272 test(vuex-persist): replace localStorage with mock implementation
  .all-contributorsrc
  package-lock.json
  package.json
  src/app/shared/plugins/vuex-persist/PersistLocalStorage.spec.ts
  src/app/shared/plugins/vuex-persist/vuex-persist.spec.ts
Labels: DX, technical depth

#273 feat: load vuex-modules on demand
  docs/guide/clean-up.md
  docs/zh-cn/guide/clean-up.md
  package-lock.json
  src/app/counter/Counter/Counter.vue
  src/app/state.ts
  src/app/store.ts
  tools/generators/ast.ts
  tools/generators/connected/connected.vue.hbs
  tools/generators/module/index.ts
  tools/generators/module/module.ts.hbs
Labels: feature, performance

#277 fix(vue-button): set fixed width for button loading
  src/app/shared/components/VueButton/VueButton.spec.ts
  src/app/shared/components/VueButton/VueButton.vue
Labels: UI, bug

#278 feat(components): add donut chart
  .storybook/config.js
  src/app/shared/components/VueDonutChart/IChartDataItem.ts
  src/app/shared/components/VueDonutChart/VueDonutChart.spec.ts
  src/app/shared/components/VueDonutChart/VueDonutChart.stories.ts
  src/app/shared/components/VueDonutChart/VueDonutChart.vue
  src/app/shared/components/icons/Icons.stories.ts
  src/app/shared/styles/DesignSystem.stories.ts
  tools/generators/component/component.spec.ts.hbs
  tools/generators/component/component.vue.hbs
  tools/generators/component/index.ts
Labels: UI, feature, help wanted

#279 feat(vue-dropdown-menu): add separator option
  src/app/shared/components/VueDropdownMenu/VueDropdownMenu.spec.ts
  src/app/shared/components/VueDropdownMenu/VueDropdownMenu.stories.ts
  src/app/shared/components/VueDropdownMenu/VueDropdownMenu.vue
Labels: components, feature

#280 feat(vue-tab-group): add keyboard accessibility
  src/app/shared/components/VueTabGroup/VueTabGroup.vue
Labels: accessibility, components, feature
