Repository vuesion/vuesion, pull requests merged in 2018-09, with the labels that each got.

#221 docs: add tutorial how to prefetch data on the server side
  docs/.vuepress/config.js
  docs/docs/prefetch-and-state-transfer.md
Labels: docs

#222 docs: add a recommended architecture section
  docs/.vuepress/public/architecture.jpg
  docs/guide/build.md
  docs/introduction.md
Labels: docs

#224 chore: update dependencies
  config/webpack.client.config.js
  package-lock.json
  package.json
  src/app/shared/components/VueAccordion/VueAccordion.spec.ts
  src/app/shared/components/VueAccordion/VueAccordionItem/VueAccordionItem.spec.ts
  src/app/shared/components/VueMarkdown/VueMarkdown.spec.ts
  src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts
  src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.spec.ts
Labels: chore

#225 docs: add guide to integrate with 3rd party UI libraries
  docs/.vuepress/config.js
  docs/guide/third-party.md
Labels: docs

#227 docs: add progressive-web-app section
  docs/.vuepress/config.js
  docs/docs/pwa.md
Labels: docs

#228 Improve 404 page wording
  src/app/app/NotFound/NotFound.vue
Labels: chore

#230 catch errors for prefetch in a unified way
  src/client/index.ts
  src/server/isomorphic.ts
Labels: enhancement

#233 docs(readme): add issue-hunt and all-contributors
  .all-contributorsrc
  README.md
Labels: docs

#229 Don't change route on 404
  cypress/integration/404.spec.ts
  cypress/integration/redirect.spec.ts
  src/app/app/routes.ts
  src/server/isomorphic.ts
  src/server/routes/SSRRoutes.ts
Labels: enhancement, feature

#239 test(vue-select): add test for disabled component
  src/app/shared/components/VueSelect/VueSelect.spec.ts
Labels: enhancement

#240 feat(vue-data-table): add custom cell renderer support
  src/app/components/Components/Components.vue
  src/app/components/FormExample/FormExample.vue
  src/app/shared/components/VueAutocomplete/VueAutocomplete.vue
  src/app/shared/components/VueDataTable/DataTableFixtures.ts
  src/app/shared/components/VueDataTable/IDataTable.ts
  src/app/shared/components/VueDataTable/VueDataTable.spec.ts
  src/app/shared/components/VueDataTable/VueDataTable.stories.ts
  src/app/shared/components/VueDataTable/VueDataTable.vue
  src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue
  src/app/shared/components/VueDataTable/VueDataTableRow/VueDataTableRow.spec.ts
  src/app/shared/components/VueDataTable/VueDataTableRow/VueDataTableRow.vue
  src/app/shared/components/VueInput/VueInput.vue
  src/app/shared/components/VueSelect/VueSelect.vue
  src/app/shared/components/VueSlider/VueSlider.vue
  src/app/shared/components/VueToggle/VueToggle.vue
  src/index.template.html
  src/static/robots.txt
Labels: enhancement, feature
