Repository vuesion/vuesion, pull requests merged in 2018-06, with the labels that each got.

#154 docs: improve wording
  docs/guide/build.md
  docs/guide/cli.md
  docs/guide/vuex.md
  docs/introduction.md
  tools/generators/module/index.ts
Labels: docs

#150 feat: add runtime config
  .github/PULL_REQUEST_TEMPLATE.md
  docs/.vuepress/config.js
  docs/docs/style-guide.md
  docs/guide/config.md
  src/app/config/IAppConfig.ts
  src/app/config/default.json
  src/app/home/Home/Home.spec.ts
  src/app/home/Home/Home.vue
  src/app/home/Stage/Stage.spec.ts
  src/app/home/Stage/Stage.vue
  src/server/routes/SSRRoutes.ts
  src/server/utils/RuntimeConfig.ts
Labels: feature

#152 feat(scripts): add script to update the vue-starter
  docs/.vuepress/config.js
  docs/guide/update.md
  package.json
  tools/scripts/.update.json
  tools/scripts/update.ts
Labels: feature

#158 fix(vue-calendar): don't display empty days as currentDay
  src/app/shared/components/VueCalendar/VueCalendar.spec.ts
  src/app/shared/components/VueCalendar/VueCalendar.vue
Labels: bug

#159 feat(vue-date-picker): open calendar on focus
  src/app/shared/components/VueDatePicker/VueDatePicker.spec.ts
  src/app/shared/components/VueDatePicker/VueDatePicker.vue
Labels: enhancement

#160 feat(vue-slider): accessibility for keyboard users
  src/app/shared/components/VueSlider/VueSlider.spec.ts
  src/app/shared/components/VueSlider/VueSlider.vue
Labels: enhancement, feature

#165 feat(components): add text truncate component
  i18n/de.json
  i18n/en.json
  i18n/pt.json
  src/app/components/Components/Components.vue
  src/app/shared/components/VueTruncate/VueTruncate.spec.ts
  src/app/shared/components/VueTruncate/VueTruncate.stories.ts
  src/app/shared/components/VueTruncate/VueTruncate.vue
Labels: enhancement, feature

#166 feat(components): add carousel
  src/app/components/Components/Components.vue
  src/app/shared/components/VueCarousel/VueCarousel.spec.ts
  src/app/shared/components/VueCarousel/VueCarousel.stories.ts
  src/app/shared/components/VueCarousel/VueCarousel.vue
  src/app/shared/styles/_variables.scss
Labels: feature

#167 feat(components): add data-table
  i18n/de.json
  i18n/en.json
  i18n/pt.json
  src/app/components/Components/Components.spec.ts
  src/app/components/Components/Components.vue
  src/app/shared/components/VueDataTable/DataTableFixtures.ts
  src/app/shared/components/VueDataTable/IDataTable.ts
  src/app/shared/components/VueDataTable/VueDataTable.spec.ts
  src/app/shared/components/VueDataTable/VueDataTable.stories.ts
  src/app/shared/components/VueDataTable/VueDataTable.vue
  src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.spec.ts
  src/app/shared/components/VueDataTable/VueDataTableHeader/VueDataTableHeader.vue
  src/app/shared/components/VueDataTable/VueDataTableRow/VueDataTableRow.spec.ts
  src/app/shared/components/VueDataTable/VueDataTableRow/VueDataTableRow.vue
  src/app/shared/components/VueDataTable/VueDataTableSearch/VueDataTableSearch.spec.ts
  src/app/shared/components/VueDataTable/VueDataTableSearch/VueDataTableSearch.vue
Labels: enhancement, feature

#168 docs(cli): add hint for paths in names
  docs/guide/cli.md
Labels: docs

#169 refactor(http-service): set store from outside to prevent circular deps
  src/app/app.ts
  src/app/shared/services/HttpService.ts
Labels: enhancement

#175 feat(components): add toggle
  package.json
  src/app/components/Components/Components.vue
  src/app/shared/components/VueToggle/VueToggle.spec.ts
  src/app/shared/components/VueToggle/VueToggle.stories.ts
  src/app/shared/components/VueToggle/VueToggle.vue
  src/app/shared/styles/_variables.scss
Labels: enhancement, feature

#176 chore: update dependencies
  package-lock.json
  package.json
  src/app/home/Stage/Stage.spec.ts
  src/app/shared/components/VueAccordion/VueAccordion.spec.ts
  src/app/shared/components/VueAccordion/VueAccordionItem/VueAccordionItem.spec.ts
  src/app/shared/components/VueAccordion/VueAccordionItem/VueAccordionItem.vue
  src/app/shared/components/VueMarkdown/VueMarkdown.spec.ts
  src/app/shared/components/VueMarkdown/VueMarkdown.vue
  src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts
  src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.spec.ts
  src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.vue
  src/server/utils/Logger.ts
  tools/scripts/update.ts
Labels: enhancement
