Repository vuesion/vuesion, pull requests merged in 2019-03, with the labels that each got.

#355 chore(storybook): align component structure with atomic design
  .vuesion/storybook/_theme.scss
  .vuesion/storybook/config.js
  .vuesion/storybook/theme.js
  package-lock.json
  package.json
  src/app/shared/components/VueAccordion/VueAccordion.stories.ts
  src/app/shared/components/VueAutocomplete/VueAutocomplete.stories.ts
  src/app/shared/components/VueBadge/VueBadge.stories.ts
  src/app/shared/components/VueBreadcrumb/VueBreadcrumb.stories.ts
  src/app/shared/components/VueButton/VueButton.stories.ts
  src/app/shared/components/VueCalendar/VueCalendar.stories.ts
  src/app/shared/components/VueCard/VueCard.stories.ts
  src/app/shared/components/VueCarousel/VueCarousel.stories.ts
  src/app/shared/components/VueCheckbox/VueCheckbox.stories.ts
  src/app/shared/components/VueCollapse/VueCollapse.stories.ts
  src/app/shared/components/VueCookieConsent/VueCookieConsent.stories.ts
  src/app/shared/components/VueDataTable/VueDataTable.stories.ts
  src/app/shared/components/VueDatePicker/VueDatePicker.stories.ts
  src/app/shared/components/VueDateRangePicker/VueDateRangePicker.stories.ts
  src/app/shared/components/VueDonutChart/VueDonutChart.stories.ts
  src/app/shared/components/VueDropdownMenu/VueDropdownMenu.stories.ts
  src/app/shared/components/VueFooter/VueFooter.stories.ts
  src/app/shared/components/VueGrid/VueGrid.stories.ts
  src/app/shared/components/VueHeadline/VueHeadline.stories.ts
  src/app/shared/components/VueInput/VueInput.stories.ts
  src/app/shared/components/VueLoader/VueLoader.stories.ts
  src/app/shared/components/VueMarkdown/VueMarkdown.stories.ts
  src/app/shared/components/VueModal/VueModal.stories.ts
  src/app/shared/components/VueNavBar/VueNavBar.stories.ts
  src/app/shared/components/VueNavigationProgress/VueNavigationProgress.stories.ts
  src/app/shared/components/VueNotificationStack/VueNotificationStack.stories.ts
  src/app/shared/components/VuePagination/VuePagination.stories.ts
  src/app/shared/components/VueSelect/VueSelect.stories.ts
  src/app/shared/components/VueSidebar/VueSidebar.stories.ts
  src/app/shared/components/VueSlider/VueSlider.stories.ts
  src/app/shared/components/VueTabGroup/VueTabGroup.stories.ts
  src/app/shared/components/VueToggle/VueToggle.stories.ts
  src/app/shared/components/VueTooltip/VueTooltip.stories.ts
  src/app/shared/components/VueTruncate/VueTruncate.stories.ts
  src/app/shared/components/icons/Icons.stories.ts
  src/app/shared/modules/auth/LoginForm/LoginForm.stories.ts
Labels: UI, components, docs

#356 fix(i18n): handle cached locales in client correctly
  src/app/app/App/App.vue
  src/app/shared/plugins/i18n/i18n.ts
Labels: bug, i18n

#357 feat(vue-button): support link as button
  src/app/shared/components/VueButton/VueButton.spec.ts
  src/app/shared/components/VueButton/VueButton.stories.ts
  src/app/shared/components/VueButton/VueButton.vue
  src/app/shared/designSystem/variables/_button.scss
Labels: UI, components, feature

#363 feat(vue-tab-group): adds reactivity to title prop
  src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts
  src/app/shared/components/VueTabGroup/VueTabGroup.vue
  src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.spec.ts
  src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.vue
Labels: UI, components, feature

#364 feat(directives): add v-sr-only
  .vuesion/storybook/config.js
  src/app/app.ts
  src/app/shared/designSystem/docs/DesignSystem.stories.ts
  src/app/shared/designSystem/global.scss
  src/app/shared/directives/Directives.stories.ts
  src/app/shared/directives/index.ts
  src/app/shared/directives/sr-only.ts
Labels: accessibility

#365 refactor(storybook): register router as global decorator
  .vuesion/storybook/config.js
  src/app/shared/components/VueBreadcrumb/VueBreadcrumb.stories.ts
  src/app/shared/components/VueButton/VueButton.stories.ts
  src/app/shared/components/VueSidebar/VueSidebar.stories.ts
Labels: DX

#366 refactor(vue-collapse): remove magic number
  src/app/shared/animations/CollapseAnimation/CollapseAnimation.spec.ts
  src/app/shared/animations/CollapseAnimation/CollapseAnimation.vue
Labels: bug, components

#367 refactor: add prop validators
  package.json
  src/app/shared/components/VueBadge/VueBadge.vue
  src/app/shared/components/VueButton/VueButton.vue
  src/app/shared/components/VueLoader/VueLoader.vue
  src/app/shared/components/utils.ts
  tsconfig.json
Labels: DX, technical depth

#370 refactor(design-system): color-palette
  .vuesion/storybook/preview-head.html
  src/app/home/EnterpriseReady/EnterpriseReady.vue
  src/app/home/QuickStart/QuickStart.vue
  src/app/home/Stage/Stage.vue
  src/app/home/UserExperience/UserExperience.vue
  src/app/shared/_design-system.scss
  src/app/shared/components/VueBadge/VueBadge.spec.ts
  src/app/shared/components/VueBadge/VueBadge.stories.ts
  src/app/shared/components/VueBadge/VueBadge.vue
  src/app/shared/components/VueButton/VueButton.spec.ts
  src/app/shared/components/VueButton/VueButton.stories.ts
  src/app/shared/components/VueButton/VueButton.vue
  src/app/shared/components/VueDonutChart/VueDonutChart.vue
  src/app/shared/components/VueLoader/VueLoader.spec.ts
  src/app/shared/components/VueLoader/VueLoader.stories.ts
  src/app/shared/components/VueLoader/VueLoader.vue
  src/app/shared/components/utils.ts
  src/app/shared/designSystem/_mixins.scss
  src/app/shared/designSystem/docs/DesignSystem.stories.ts
  src/app/shared/designSystem/docs/components/BrandColors.vue
  src/app/shared/designSystem/docs/components/ColorPalette.vue
  src/app/shared/designSystem/typo.scss
  src/app/shared/designSystem/variables/_badge.scss
  src/app/shared/designSystem/variables/_brand.scss
  src/app/shared/designSystem/variables/_button.scss
  src/app/shared/designSystem/variables/_color-palette.scss
  src/app/shared/designSystem/variables/_input.scss
  src/app/shared/designSystem/variables/_loader.scss
  src/app/shared/designSystem/variables/_nav-bar.scss
  src/app/shared/designSystem/variables/_typo.scss
  src/index.template.html
Labels: DX, accessibility, components, technical depth

#373 refactor(vue-button): add dynamic variations
  src/app/shared/components/VueButton/VueButton.spec.ts
  src/app/shared/components/VueButton/VueButton.stories.ts
  src/app/shared/components/VueButton/VueButton.vue
  src/app/shared/components/VueCookieConsent/VueCookieConsent.vue
  src/app/shared/components/utils.ts
  src/app/shared/designSystem/variables/_button.scss
Labels: DX

#374 refactor(vue-badge): add dynamic variations
  src/app/shared/components/VueBadge/VueBadge.spec.ts
  src/app/shared/components/VueBadge/VueBadge.stories.ts
  src/app/shared/components/VueBadge/VueBadge.vue
  src/app/shared/designSystem/variables/_badge.scss
Labels: DX

#375 refactor(vue-loader): add dynamic variations
  src/app/shared/components/VueLoader/VueLoader.spec.ts
  src/app/shared/components/VueLoader/VueLoader.stories.ts
  src/app/shared/components/VueLoader/VueLoader.vue
  src/app/shared/designSystem/variables/_loader.scss
Labels: DX

#376 fix(vue-modal): remove min-width
  src/app/shared/components/VueModal/VueModal.vue
  src/app/shared/designSystem/variables/_modal.scss
  src/app/shared/modules/auth/LoginForm/LoginForm.vue
Labels: bug

#383 refactor: re-branding
  README.md
  docs/.vuepress/config.js
  docs/.vuepress/override.styl
  docs/.vuepress/public/logo.png
  docs/.vuepress/style.styl
  docs/guide/contribute.md
  docs/zh-cn/guide/contribute.md
  src/app/app/App/App.vue
  src/app/home/DevEx/DevEx.spec.ts
  src/app/home/DevEx/DevEx.vue
  src/app/home/EnterpriseReady/EnterpriseReady.spec.ts
  src/app/home/EnterpriseReady/EnterpriseReady.vue
  src/app/home/Home/Home.spec.ts
  src/app/home/Home/Home.vue
  src/app/home/QuickStart/QuickStart.spec.ts
  src/app/home/QuickStart/QuickStart.vue
  src/app/home/Stage/Stage.vue
  src/app/home/UserExperience/UserExperience.spec.ts
  src/app/home/UserExperience/UserExperience.vue
  src/app/home/components/HomeSection/HomeSection.stories.ts
  src/app/home/components/HomeSection/HomeSection.vue
  src/app/shared/animations/CircleAnimation.ts
  src/app/shared/components/VueDonutChart/VueDonutChart.vue
  src/app/shared/components/VueNavBar/VueNavBar.vue
  src/app/shared/components/icons/Icons.stories.ts
  src/app/shared/components/icons/VueIconVuesion/VueIconVuesion.vue
  src/app/shared/designSystem/docs/components/ColorPalette.vue
  src/app/shared/designSystem/global.scss
  src/app/shared/designSystem/reset.scss
  src/app/shared/designSystem/variables/_brand.scss
  src/app/shared/designSystem/variables/_color-palette.scss
  src/app/shared/designSystem/variables/_grid.scss
  src/app/shared/designSystem/variables/_select.scss
  src/app/shared/designSystem/variables/_sidebar.scss
  src/static/browserconfig.xml
  src/static/color-palette.jpg
  src/static/icon-128x128.png
  src/static/icon-144x144.png
  src/static/icon-152x152.png
  src/static/icon-192x192.png
  src/static/icon-384x384.png
  src/static/icon-512x512.png
  src/static/icon-72x72.png
  src/static/icon-96x96.png
  src/static/logo.png
  src/static/manifest.json
Labels: chore

#384 chore: update README.md
  .all-contributorsrc
  README.md
Labels: chore

#372 feat(storybook): update storybook
  .vuesion/storybook/config.js
  .vuesion/storybook/theme.js
  .vuesion/storybook/webpack.config.js
  package-lock.json
  package.json
Labels: DX, chore
