Repository vuesion/vuesion, pull requests merged in 2020-03, with the labels that each got.

#496 test(calendar): corrected existing test
  src/app/shared/components/VueCalendar/VueCalendar.spec.ts
Labels: technical depth

#498 chore: update dependencies
  package-lock.json
  package.json
  src/app/example/form/FormExample/FormExample.spec.ts
  src/app/shared/components/VueAccordion/VueAccordionItem/VueAccordionItem.spec.ts
  src/app/shared/components/VueButton/VueButton.vue
  src/app/shared/components/VueCalendar/VueCalendar.spec.ts
  src/app/shared/components/VueCheckbox/VueCheckbox.spec.ts
  src/app/shared/components/VueCookieConsent/VueCookieConsent.spec.ts
  src/app/shared/components/VueDataTable/VueDataTable.spec.ts
  src/app/shared/components/VueDatePicker/VueDatePicker.spec.ts
  src/app/shared/components/VueDropdownMenu/VueDropdownMenu.spec.ts
  src/app/shared/components/VueInput/VueInput.spec.ts
  src/app/shared/components/VueMarkdown/VueMarkdown.spec.ts
  src/app/shared/components/VuePagination/VuePagination.spec.ts
  src/app/shared/components/VueSidebar/VueSidebar.spec.ts
  src/app/shared/components/VueStarRating/VueStarRating.spec.ts
  src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts
  src/app/shared/components/VueTabGroup/VueTabItem/VueTabItem.spec.ts
  src/app/shared/components/VueTextarea/VueTextarea.spec.ts
  src/app/shared/components/VueToggle/VueToggle.spec.ts
  src/app/shared/components/VueTooltip/VueTooltip.spec.ts
  src/app/shared/modules/auth/LoginForm/LoginForm.spec.ts
Labels: chore

#499 chore: upgrade prettier to v2
  package-lock.json
  package.json
  src/app/shared/components/VueAutocomplete/VueAutocomplete.vue
  src/app/shared/components/VueCalendar/VueCalendar.spec.ts
  src/app/shared/components/VueStarRating/VueStarRating.spec.ts
  src/app/shared/components/VueTabGroup/VueTabGroup.spec.ts
Labels: chore

#500 refactor(vue-input): use composition api + re-design
  .vuesion/jest.config.ts
  .vuesion/storybook/_theme.scss
  package-lock.json
  package.json
  src/app/shared/components/VueButton/VueButton.vue
  src/app/shared/components/VueInput/VueInput.spec.ts
  src/app/shared/components/VueInput/VueInput.stories.ts
  src/app/shared/components/VueInput/VueInput.vue
  src/app/shared/components/VueSelect/VueSelect.vue
  src/app/shared/components/VueTextarea/VueTextarea.vue
  src/app/shared/composables/use-intersection-observer.spec.ts
  src/app/shared/composables/use-intersection-observer.ts
  src/app/shared/designSystem/themes/dark.scss
  src/app/shared/designSystem/themes/light.scss
  src/app/shared/designSystem/variables/_input.scss
  src/app/shared/testing/test-utils.ts
  src/server/isomorphic.ts
Labels: DX, UI, components
